"""Phase 5 live integration — Gmail write-ops on egor.titt@gmail.com.

Run with:
    LIVE_GOOGLE_TESTS=1 uv run pytest tests/integration/test_gmail_phase5_live.py -v

Safety notes:
  - Drafts are CREATED but never SENT. Test exits with drafts in the user's
    drafts folder; clean up there manually if you want.
  - modify_labels / archive / mark_read tests need a real message to act on.
    Strategy: send a self-message-as-draft via create_draft, then operate on
    that draft's message_id (which Gmail assigns even before send). For full
    integration we need an actual inbox message, so we look up the most
    recent message in the inbox to act on — but ONLY for label-mark tests
    which are reversible.
  - Filters: we create a test filter pointing to a fake address, verify it
    appears in list, delete it. Reversible.
"""
import pytest

pytestmark = pytest.mark.integration


@pytest.fixture(autouse=True)
def _probe_gmail_api(claude_test_account):
    """Skip the module if Gmail API isn't enabled / scopes don't cover the call.

    The user has to manually accept Gmail API's TOS in the Cloud Console
    (`https://console.cloud.google.com/apis/library/gmail.googleapis.com?project=148389149001`)
    before these can run. We probe with a cheap `users().getProfile()` call.
    """
    from src.tools import gmail
    try:
        gmail._service(claude_test_account).users().getProfile(userId="me").execute()
    except Exception as e:
        msg = str(e)
        if "accessNotConfigured" in msg or "has not been used in project" in msg:
            pytest.skip("Gmail API not enabled on the GCP project (accept TOS in Cloud Console)")
        if "insufficient" in msg.lower():
            pytest.skip("Gmail token lacks scope — re-OAuth needed via /accounts UI")
        raise


def _make_inbox_test_message(account: str) -> str:
    """Create + send a draft to self, returning the resulting message_id once
    Gmail has processed it. Used for tests that need a real inbox message
    (modify_labels round-trip). The message ends up in BOTH Sent AND Inbox
    because we email ourselves.
    """
    from src.tools import gmail
    draft = gmail.create_draft(
        to="egor.titt@gmail.com",
        subject="[CLAUDE-TEST phase-5] integration probe",
        body="Auto-generated by Phase 5 integration tests. Safe to delete.",
        account=account,
    )
    sent = gmail.send_draft(draft["draft_id"], account=account)
    return sent["sent_message_id"]


# ---------- get_thread ----------

def test_get_thread_on_self_message(claude_test_account):
    """Create a real inbox message, fetch its thread, ensure structure intact."""
    from src.tools import gmail
    msg_id = _make_inbox_test_message(claude_test_account)
    # Get the message to find its thread_id
    msg = gmail.get_message(msg_id, account=claude_test_account)
    thread_id = msg["thread_id"]
    thread = gmail.get_thread(thread_id, account=claude_test_account)
    assert thread["_meta"]["message_count"] >= 1
    # At least one message should be present and have our subject
    subjects = [m.get("subject", "") for m in thread["messages"]]
    assert any("[CLAUDE-TEST phase-5]" in s for s in subjects)


# ---------- reply (draft-only) ----------

def test_reply_creates_draft_with_threading(claude_test_account):
    """Reply to a real message → draft should appear with In-Reply-To set."""
    from src.tools import gmail
    msg_id = _make_inbox_test_message(claude_test_account)
    result = gmail.reply(msg_id, "Это тестовый ответ из Phase 5", account=claude_test_account)
    assert result["draft_id"]
    assert result["subject"].startswith("Re:")


# ---------- forward (draft-only) ----------

def test_forward_creates_draft(claude_test_account):
    from src.tools import gmail
    msg_id = _make_inbox_test_message(claude_test_account)
    result = gmail.forward(
        msg_id,
        to="egor.titt@gmail.com",
        body="forwarding for archival",
        account=claude_test_account,
    )
    assert result["draft_id"]
    assert result["subject"].startswith("Fwd:")


# ---------- modify_labels round-trip ----------

def test_archive_then_restore_inbox(claude_test_account):
    """Archive a message (remove INBOX), then put it back, verify state."""
    from src.tools import gmail
    msg_id = _make_inbox_test_message(claude_test_account)
    # baseline: should have INBOX
    msg = gmail.get_message(msg_id, account=claude_test_account)
    assert "INBOX" in msg["labels"]

    # archive
    after_archive = gmail.archive(msg_id, account=claude_test_account)
    assert "INBOX" not in after_archive["labels_after"]

    # restore: add INBOX back
    after_restore = gmail.modify_labels(msg_id, add=["INBOX"], account=claude_test_account)
    assert "INBOX" in after_restore["labels_after"]


def test_mark_read_unread_round_trip(claude_test_account):
    from src.tools import gmail
    msg_id = _make_inbox_test_message(claude_test_account)
    # New self-message: likely has UNREAD initially
    after_read = gmail.mark_read(msg_id, account=claude_test_account)
    assert "UNREAD" not in after_read["labels_after"]
    after_unread = gmail.mark_unread(msg_id, account=claude_test_account)
    assert "UNREAD" in after_unread["labels_after"]


# ---------- batch_modify ----------

def test_batch_modify_archives_two_messages(claude_test_account):
    from src.tools import gmail
    m1 = _make_inbox_test_message(claude_test_account)
    m2 = _make_inbox_test_message(claude_test_account)
    result = gmail.batch_modify([m1, m2], remove=["INBOX"], account=claude_test_account)
    assert result["count"] == 2
    # Restore
    gmail.batch_modify([m1, m2], add=["INBOX"], account=claude_test_account)


# ---------- filters ----------

def test_filter_create_list_delete(claude_test_account):
    from src.tools import gmail

    # Create a filter that catches a deliberately-unused subject
    test_subject = "ZZZ-CLAUDE-TEST-FILTER-9d2f"
    created = gmail.create_filter(
        criteria={"subject": test_subject},
        add_labels=["STARRED"],
        account=claude_test_account,
    )
    fid = created["filter_id"]
    try:
        listing = gmail.list_filters(account=claude_test_account)
        ids = [f["id"] for f in listing["filters"]]
        assert fid in ids
    finally:
        gmail.delete_filter(fid, account=claude_test_account)
        # Confirm it's gone
        after = gmail.list_filters(account=claude_test_account)
        assert fid not in [f["id"] for f in after["filters"]]
